# Generated by Django 3.1.1 on 2020-09-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Boboo TVVV'),
            preserve_default=False,
        ),
    ]
