# Generated by Django 3.1.1 on 2020-09-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200923_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='skrrrrr', max_length=100),
            preserve_default=False,
        ),
    ]
