# Generated by Django 3.1.1 on 2020-09-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
    ]
