# Generated by Django 3.1.1 on 2020-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='/media/images/Admin_page.png', upload_to='images/'),
        ),
    ]
