# Generated by Django 3.1.1 on 2020-09-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200929_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
        migrations.AddField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
