# Generated by Django 3.1.1 on 2020-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200929_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_photo',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos'),
        ),
    ]
